### ISSUE TITLE
License

### ISSUE THREAD

**Issue by s1arsky** [stefonrose/ZombieSimulation#1]
Consider adding license since from readme.md is implied that you want someone to run your code.

**Comment by jaggiJ** [comment]
Ok it run on windows after pip install matplotlib.

**Comment by jaggiJ** [comment]
Ah, it runs but it only iterates population and quits:
[...]
25: Person of class Susceptible located at (10,3)
C:\Users\goldalex\Downloads\ZombieSimulation-master>
